### PR TITLE
Work around false error when claiming interface to fix firmware flashing on MacOS

### LINKED ISSUE #1892: Firmware flashing not working on MacOS with master
Not sure exactly when this problem started, but I remember seeing it in the past so I don't think it's been recently introduced. On MacOS after clicking the "Flash" button the board will switch to DFU mode and be detected, but flashing fails. Not errors, just "Device opened", "Device closed" messages immediately. Looking at the console I see:
```
SERIAL: Connection opened with ID: 1, Baud: 115200
MSPConnector.js:55 Connected
stm32.js:152 Looking for capabilities via MSP
stm32.js:163 no flash bootloader detected
serial.js:265 SERIAL: Connection with ID: 1 closed, Sent: 19 bytes, Received: 85 bytes
MSPConnector.js:71 Disconnected
port_handler.js:32 PortHandler - Removed: /dev/cu.usbmodem221,/dev/tty.usbmodem221
stm32usbdfu.js:95 USB DFU detected with ID: 2
stm32usbdfu.js:134 Device opened with Handle ID: 7
stm32usbdfu.js:108 reporting chrome error: Error claiming interface.
stm32usbdfu.js:160 Failed to claim USB device!
stm32usbdfu.js:1080 Script finished after: 0.012 seconds
stm32usbdfu.js:164 Claimed interface: 0
stm32usbdfu.js:178 Released interface: 0
main.html#progressbar:1 Unchecked runtime.lastError: Error releasing interface.
stm32usbdfu.js:149 Device closed with Handle ID: 7
stm32usbdfu.js:108 reporting chrome error: No such connection.
main.html#progressbar:1 Error handling response: TypeError: Cannot read property 'resultCode' of undefined
    at chrome-extension://ajdoecjhplhoahggfmgflfnlechcljoc/js/protocols/stm32usbdfu.js:274:72
```

with the relevant errors I chink being:
```
stm32usbdfu.js:108 reporting chrome error: Error claiming interface.
stm32usbdfu.js:160 Failed to claim USB device!
```

I'm not 100% sure but I thought that we had seen something similar in the past that turned out to be related to bugs in a NW.js version and needing to use a later.

Also probably related: Clicking the "Exit DFU Mode" button doesn't work and generates the same errors.

### PR DESCRIPTION
**Pull request by etracer65**
Fixes #1892 

The error check after attempting to claim the USB interface was falsely indicating failure on MacOS even though it was working properly. Tried all available versions of NW.js (including beta) and none resolve the problem. The problem only seems to affect MacOS.

The error check after claiming the interface is suppressed for MacOS to work around the problem. Risk is low because even if the climing of the interface failed the worst that could happen is flash fails anyway.

Hopefully there will be some future version of NW.js that resolves the problem and we can remove this workaround later (tested through 0.45.0-beta1 so far).

### CODE REVIEW

File: src/js/protocols/stm32usbdfu.js [hunk 1]
```diff
@@ -156,7 +156,9 @@ STM32DFU_protocol.prototype.claimInterface = function (interfaceNumber) {
     var self = this;
 
     chrome.usb.claimInterface(this.handle, interfaceNumber, function claimed() {
-        if(self.checkChromeError()) {
+        // Don't perform the error check on MacOS at this time as there seems to be a bug
+        // where it always reports an error even though it works correctly.
+        if (self.checkChromeError() && (GUI.operating_system !== "MacOS")) {
```
Comment (mikeller) [inline src/js/protocols/stm32usbdfu.js]: Since the type of error that is thrown in MacOS is still logged to the console, it might make sense to add the type of error to the comment, so somebody else investigating a problem will know if this is the same or something different.

Comment (etracer65) [reply src/js/protocols/stm32usbdfu.js]: I'm not sure "Error claiming interface" is too helpful, but ok.

Comment (mikeller) [reply src/js/protocols/stm32usbdfu.js]: Not very informative - but if it helps somebody eliminate that an error they are getting is not the one classified as 'has no impact' then that's helpful.

Comment (etracer65) [reply src/js/protocols/stm32usbdfu.js]: Updated the comment.
