### PR TITLE
Fix beeper config initial load and bulk toggle refresh

### LINKED ISSUE #4877: beeper configuration loading issue
### Describe the bug

The configurator doesn't load actual beeper configuration on connection to the configuration tab instead it uses default(all enabled). When you navigate from another tab, it loads properly.
Disable and enable all buttons are also broken.

### To Reproduce

-activate "reopen last tab on connect"
-change beeper config (deactivate some beeps)
-save reboot
-on connection you'll see all options still enabled
-navigate to any tab and return back - you'll see your actual config

### Expected behavior

you see your actual config instead of default on connection

### App version

latest master (please return the ability co select and paste values from app))

### Flight controller configuration

```txt

```

### Add any other context about the problem that you think might be relevant here

_No response_

### PR DESCRIPTION
**Pull request by Erics1337**
## Summary
- sync beeper state from store immediately after MSP_BEEPER_CONFIG and during initializeUI
- make initializeUI resilient if sensorTypes fails so beeper state still initializes
- refresh existing Switchery controls on GUI.switchery so Enable all and Disable all updates are reflected

## Root cause
- first-load beeper state regression appears tied to async initialization ordering introduced after #4799, not the #4799 store refactor itself
- existing switch controls were not re-positioned after reactive state changes, so bulk beeper toggles appeared broken

## Verification
- reproduced with reopen last tab on connect enabled
- confirmed saved beeper selections now render correctly on first open of Configuration tab
- confirmed both beeper and dshot Enable all and Disable all controls work

Fixes #4877
Related comment: https://github.com/betaflight/betaflight-configurator/issues/4877#issuecomment-3934100345

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error handling when loading sensor types with graceful fallback and warning logs.
  * Synchronized beeper-related UI state earlier to prevent inconsistent UI during initialization.

* **Refactor**
  * Centralized beeper state synchronization into a single helper for consistent UI behavior.
  * Consolidated toggle/switch initialization into a unified data-driven flow that reuses existing instances and simplifies setup.

### CODE REVIEW

File: src/components/tabs/ConfigurationTab.vue [hunk 1]
```diff
@@ -1113,6 +1129,7 @@ export default defineComponent({
                 await Promise.resolve(); // Start chain
                 await MSP.promise(MSPCodes.MSP_FEATURE_CONFIG);
                 await MSP.promise(MSPCodes.MSP_BEEPER_CONFIG);
+                syncBeeperStateFromStore();
```
Comment (haslinghuis) [inline src/components/tabs/ConfigurationTab.vue]: Is this line not redundant, i.e. handled in InitializeUI ?

Comment (Erics1337) [reply src/components/tabs/ConfigurationTab.vue]: > Is this line not redundant, i.e. handled in InitializeUI ?

Good catch, you’re right.

That `syncBeeperStateFromStore()` call after `MSP_BEEPER_CONFIG` was added as a defensive step while diagnosing the first-load regression (to apply beeper masks immediately in case later async init failed). After hardening `initializeUI()` to sync beeper state early and continue on `sensorTypes()` failure, that call is now redundant.

I’ve removed it and kept the single sync path in `initializeUI()`.

**Comment by mituritsyn** [comment]
The problem has been solved. Thank you.
