### PR TITLE
cordova_serial.requestPermission() driver fix

### LINKED ISSUE #2437: Flight controllers requiring CP2104 driver not working in android
I´ve installed betaflight configurator in a android device and tried to connect to a FC with an USB UART built-in.
I did the same test for 3 different flight controller. Two of them (SPracingF3 and Naze32) with Sil2104 ICs and one with I believe native usb support (CrazyBeeF3). The last one is working properly, the first ones dont. When I try to connect to the FCs I got a popup message "do you want to allow Betaflight Configurator access to CP2104 USB to UART Bridge Controller?" and two buttons below "cancel" / "accept". After clickling on accept the tool crashes and get closed by android task manager.
Is these "legacy" hardware not supported or is it just a bug?
I´ve got android 10 and betaflight configurator 10.7.0

### PR DESCRIPTION
**Pull request by danybd**
Fight controller based on silabs CP2104 was not working as function call cordova_serial.requestPermission() without specify the driver parameter uses the default driver "CdcAcmSerialDriver" which is the wrong when usb-uart chip is a CP2104. This chip requires the driver "Cp21xxSerialDriver". It fixes #2437

### CODE REVIEW

File: src/js/cordova_chromeapi.js [hunk 1]
```diff
@@ -60,6 +60,13 @@ const chromeapiSerial = {
         stopBits: 'one',
         ctsFlowControl: false,
     },
+    getDriver: function(vid, pid) {
+        if (vid === 4292 && pid === 60000) {
+            return 'Cp21xxSerialDriver'; //for Silabs CP2102 and all other CP210x
+        }  else {
+            return undefined;
```
Comment (haslinghuis) [inline src/js/cordova_chromeapi.js:67]: maybe assign the default here:
```suggestion
            return 'CdcAcmSerialDriver';
```

**Review by haslinghuis — CHANGES_REQUESTED** [review]
Should also add the device to `./cordova/usb_device_filter.xml`:
```
 <usb-device vendor-id="4292" product-id="60000" /> <!-- 0xea60: CP2102 and other CP210x single port devices -->
```

File: src/js/cordova_chromeapi.js (hunk 1 above)
Comment (haslinghuis) [reply src/js/cordova_chromeapi.js:67]: @danybd Did you also test your patch if the connection with a `VCP` device is still working?

Comment (danybd) [reply src/js/cordova_chromeapi.js:67]: > @danybd Did you also test your patch if the connection with a `VCP` device is still working?

yes I did. I tested both of them.

**Comment by danybd** [comment]
> Should also add the device to `./cordova/usb_device_filter.xml`:
> 
> ```
>  <usb-device vendor-id="4292" product-id="60000" /> 
> ```
done

**Review by haslinghuis — DISMISSED** [review]

**Review by McGiverGim — APPROVED** [review]
Not tested, but it seems ok to me.

**Review by mikeller — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> PASS
 - PR is not in draft -> PASS
 - Assigned to a milestone -> PASS
 - cooling off period lapsed (15/03/2021 12:50:09) -> PASS
 - commit count less or equal to three (4 commits) -> FAIL
 - 'Don't merge' label NOT found -> PASS
 - 'Needs coordination with betaflight' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> FAIL
 - assigned to an approver (None) -> FAIL
 - approver count at least three (3 approvers) -> PASS

**Comment by Asizon** [comment]
@danybd can you please Squash your commits into only one?

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> PASS
 - PR is not in draft -> PASS
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> FAIL
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> FAIL
 - PR is not in draft -> PASS
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> FAIL
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

**Review by haslinghuis — APPROVED** [review]

**Review by Asizon — APPROVED** [review]

**Review by mikeller — APPROVED** [review]

**Comment by blckmn** [comment]
AUTOMERGE: (PASS)
 - Github identifies PR as mergeable -> PASS
 - PR is not in draft -> PASS
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

**Comment by haslinghuis** [comment]
@danybd Thanks for your contribution. Sorry it took so long but we are in a process to automate some processes. Here is the release:

https://github.com/betaflight/betaflight-configurator-nightlies/releases/tag/v20210616.3059

**Comment by danybd** [comment]
@haslinghuis happy to make betaflight a little bit better :) Do you know guys when is the release 10.8.0 planned (if 10.8.0 is actually the next version)?
