### PR TITLE
Fix elrs connection

### LINKED ISSUE #3050: ELRS device dissapears after a second
### Describe the bug

After the configurator starts it discovers the elrs 3.0 device but it dissappears from the port list after a second. Based on my testings this bug happens after in the port_handler.js the `TCP_CHECK_INTERVAL` expires and the tcpCheck() method called in line 107.
image

If I power my drone after the configurator loaded than it connects automatically but then it disconnect.
image

I can connect to my drone manually via wifi.
@freasy can you check?
### To Reproduce

Plug the drone in and check the configurator.

### Expected behavior

Not dissappearing.

### Configurator version

10.9, master, Windows 11

### PR DESCRIPTION
**Pull request by ASDosjani**
The previous .get() method was broken, `self.mdnsBrowser.init` was pointless and the `remove()` function does not delete the services properly.
This PR hopefully fixes these.
On android it doesn't remove offline devices but disables and pings them while they become online again. I also copied the connect button click code from serial backend only to be unified.

Thanks to @haslinghuis the whole mdns code went to a different class thus keeping the code clean.

Fixes #3050
Merges: #3094

### CODE REVIEW

File: src/js/port_handler.js [hunk 1]
```diff
@@ -82,13 +77,16 @@ PortHandler.initialize = function () {
                 tcpPorts.forEach(function (port) {
                     const removePort = () => {
                         self.mdnsBrowser.services = self.mdnsBrowser.services.filter(s => s.fqdn !== port.fqdn);
+                        self.mdnsBrowser.browser.services=[];
```
Comment (howels) [inline src/js/port_handler.js:80]: @ASDosjani you might want to check with 2 eLRS RX connected and check this doesn't mess with the other eLRS port when one is disconnected.

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

**Comment by freasy** [comment]
@ASDosjani i would not omit the "init" check. If this file ever gets imported twice, you start two mdns resolver. I dont know how that will work out.

But nice work!

I would reinsert the init check and clean some stuff up. May i give some input?

File: src/js/mdns_discovery.js [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+    }, TCP_CHECK_INTERVAL);
+};
+
+MdnsDiscovery.tcpCheck = function() {
+    const self = this;
+
+    if (!self.tcpCheckLock) {
+        self.tcpCheckLock = true;
+        if (self.initialPorts?.length > 0) {
+            const tcpPorts = self.initialPorts.filter(p => p.path.startsWith('tcp://'));
```
Comment (haslinghuis) [inline src/js/mdns_discovery.js:69]:
```suggestion
        if (PortHandler.initialPorts?.length > 0) {
            const tcpPorts = PortHandler.initialPorts.filter(p => p.path.startsWith('tcp://'));
```

Comment (ASDosjani) [reply src/js/mdns_discovery.js]: Thanks, I forgot it

**Comment by howels** [comment]
From testing the porthandler is adding mDNS-based ports but not removing them when the RX is powered off. Tested on Linux and Android.

File: src/js/mdns_discovery.js [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+        if (!GUI.isCordova()){
+            self.mdns_timer = setInterval(() => {
+                if (!GUI.connected_to && self.mdnsBrowser.browser) {
+                    self.mdnsBrowser.browser.update();
+                }
+            }, MDNS_INTERVAL);
+        }
+    }
+
+    setTimeout(() => {
```
Comment (haslinghuis) [inline src/js/mdns_discovery.js:58]:
```suggestion
    setInterval(() => {
```

Comment (ASDosjani) [reply src/js/mdns_discovery.js:58]: Good catch, we didn't copy the timeout which calls itself but this is a nicer sollution

**Comment by howels** [comment]
Both Android and Linux versions are now correctly adding and removing TCP ports when the eLRS RX goes online/offline.

File: src/js/mdns_discovery.js [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+                        txt: service.txtRecord,
+                        fqdn: `${service.name}._http._tcp.local.`,
+                        ready: true,
+                    });
+                }
+                else if (action==='added' && service.name.includes("elrs_rx")) {
+                    //restart zeroconf if service ip doesn't arrive in 1000ms
+                    setTimeout(()=>{
+                        if (self.mdnsBrowser.services.length===0 || self.mdnsBrowser.services.filter(s=>s.fqdn===`${service.name}._http._tcp.local.`)[0].ready===false)
+                        {
```
Comment (haslinghuis) [inline src/js/mdns_discovery.js:41]: Code style. Opening curly brace needs on the end of the if statement

File: src/js/mdns_discovery.js [hunk 5]
```diff
@@ -0,0 +1,134 @@
...
+    if (GUI.isCordova()) {
+        const zeroconf = cordova.plugins.zeroconf;
+
+        function reinit(){
+            zeroconf.registerAddressFamily = 'ipv4'; // or 'ipv6' ('any' by default)
+            zeroconf.watchAddressFamily = 'ipv4'; // or 'ipv6' ('any' by default)
+            zeroconf.watch("_http._tcp.", "local.", (result) => {
+                const action = result.action;
+                const service = result.service;
+                if (action==='resolved' && service.name.includes("elrs_rx")) {
```
Comment (haslinghuis) [inline src/js/mdns_discovery.js:28]: Give === some space

File: src/js/mdns_discovery.js [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+                    console.log("Zeroconf Service Changed", service);
+                    self.mdnsBrowser.services.push({
+                        addresses: service.ipv4Addresses,
+                        txt: service.txtRecord,
+                        fqdn: `${service.name}._http._tcp.local.`,
+                        ready: true,
+                    });
+                }
+                else if (action==='added' && service.name.includes("elrs_rx")) {
```
Comment (haslinghuis) [inline src/js/mdns_discovery.js:37]: 👾

File: src/js/mdns_discovery.js [hunk 7]
```diff
@@ -0,0 +1,134 @@
...
+                    //restart zeroconf if service ip doesn't arrive in 1000ms
+                    setTimeout(()=>{
```
Comment (haslinghuis) [inline src/js/mdns_discovery.js:39]: 👾

File: src/js/mdns_discovery.js [hunk 8]
```diff
@@ -0,0 +1,134 @@
...
+                    success: () => {
+                        self.mdnsBrowser.services = self.mdnsBrowser.services
+                        .map(s=> {
+                            if (s.fqdn === service.fqdn) {
+                                return {...s, ready: true};
+                            }
+                            return s;
+                            });
+                    },
+                    error: ()=>{},
```
Comment (haslinghuis) [inline src/js/mdns_discovery.js:80]: 👾

File: src/js/mdns_discovery.js [hunk 9]
```diff
@@ -0,0 +1,134 @@
...
+    if (!self.tcpCheckLock) {
+        self.tcpCheckLock = true;
+        if (PortHandler.initialPorts?.length > 0) {
+            const tcpPorts = PortHandler.initialPorts.filter(p => p.path.startsWith('tcp://'));
+            tcpPorts.forEach(function (port) {
+                const removePort = () => {
+                    if (GUI.isCordova()) {
+                        //disable offline services instead of removing them
+                        self.mdnsBrowser.services = self.mdnsBrowser.services
+                        .map(s=> {
```
Comment (haslinghuis) [inline src/js/mdns_discovery.js:107]: 👾

**Review by haslinghuis — APPROVED** [review]

**Review by sugaarK — APPROVED** [review]

**Comment by roroid** [comment]
Captură de ecran din 2022-12-02 la 22 29 57
I give it a go but still no connection.

**Comment by ASDosjani** [comment]
> 

Hi, can you join to the discord server? I would be glad if you could make some test.

**Comment by roroid** [comment]
> Hi, can you join to the discord server? I would be glad if you could make some test.

Sure. Just to arive home and I will make a test with the latest night build to see if it works. Thank you for your help.

**Comment by ASDosjani** [comment]
> > Hi, can you join to the discord server? I would be glad if you could make some test.
> 
> Sure. Just to arive home and I will make a test with the latest night build to see if it works. Thank you for your help.

It probably won't work, it's only working for one of my quad, I don't know what's the problem exactly. After I reflashed my quad it started working again. My name on BF discord server is ASDosjani as well, please reach out to me.
