### PR TITLE
Fix: maps and `dist/dist/dist` builds

### LINKED ISSUE #3681: GPS map not showing after PR 3597
### Describe the bug

Recent rollup changes do not show the map.

### To Reproduce

N/A

### Expected behavior

Map shows when reverting 8f85f08

### Configurator version

master

### Flight controller configuration

_No response_

### Add any other context about the problem that you think might be relevant here

_No response_

### PR DESCRIPTION
**Pull request by chmelevskij**
* fixes `dist/dist/dist/dist` build bug
* load in `map.js` for gps tab to work as expected

Resolves #3681

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

File: gulpfile.js [hunk 1]
```diff
@@ -124,7 +124,7 @@ gulp.task('apps', appsBuild);
 const debugAppsBuild = gulp.series(gulp.parallel(clean_debug, gulp.series(clean_dist, debugDistBuild)), debug, gulp.series(cordova_apps(false)), gulp.parallel(listPostBuildTasks(DEBUG_DIR)));
 
 const debugBuildNoStart = gulp.series(debugDistBuild, debug, gulp.parallel(listPostBuildTasks(DEBUG_DIR)));
-const debugBuild = gulp.series(debugBuildNoStart, start_debug);
+const debugBuild = gulp.series(clean_dist, debugBuildNoStart, start_debug);
```
Comment (McGiverGim) [inline gulpfile.js:127]: The clean_dist was removed from the debug build to accelerate the build while testing. There isn't a better fix?

Comment (haslinghuis) [reply gulpfile.js:127]: This step takes only a 1 or 2 seconds on my system.

**Review by haslinghuis — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]

File: gulpfile.js (hunk 1 above)
Comment (nerdCopter) [reply gulpfile.js:127]: i don't mind cleaning as well. my alias command does this manually, nice to return, imho.

Comment (haslinghuis) [reply gulpfile.js:127]: We can do any optimization after we fix this bug.

Comment (McGiverGim) [reply gulpfile.js:127]: The problem is not the clean_dist command, at least before the change, the rest of the debugBuild was a lot faster if the files were there and a lot slower if it must start from scratch. I don't know if this applies to the current version, the build has changed a lot since then.

Comment (McGiverGim) [reply gulpfile.js:127]: More info here: https://github.com/betaflight/betaflight-configurator/pull/1144

Comment (haslinghuis) [reply gulpfile.js:127]: `yarn && yarn start` the second times takes about 10 seconds here.

Comment (nerdCopter) [reply gulpfile.js:127]: that's fair too. i;ve not seen problems, since i always force a clean.  this line can be reverted if desired.

Comment (haslinghuis) [reply gulpfile.js:127]: Then we get the repeating dist dist dist issue

**Comment by ctzsnooze** [comment]
@chmelevskij - I'd be really grateful if you could possibly make a PR that would enable the 'satellite' or 'terrain' view of the map - is that possible?
