### PR TITLE
Fix and consolidate check for chrome.runtime.lastError

### LINKED ISSUE #2350: unchecked runtime.lastError: User Cancelled
FYI
@Asizon found an issue while using Font Manager.

To reproduce: cancel the file explorer window while using Open Font File or Select Custom Image.

IMG_20201218_085848

Debug:
Line 2936 FONT.openFontFile() ==> line 175 parameter FileEntry at extension::fileEntryBindingUtil:46

This is just a reminder so we don't forget. Will look into this.

### PR DESCRIPTION
**Pull request by haslinghuis**
`Fixes #2350`

- Fixes a misplaced error check in osd tab where an argument is accessed after the user cancels the operation.
- Added missing error checking in tethered logging tab.
- Created `utils/common.js` for common used functions like `checkChromeRuntimeError()` and changed codebase to use this function.

Fixes: #2350

### CODE REVIEW

File: src/js/tabs/logging.js [hunk 1]
```diff
@@ -102,6 +102,11 @@ TABS.logging.initialize = function (callback) {
         ConfigStorage.get('logging_file_entry', function (result) {
             if (result.logging_file_entry) {
                 chrome.fileSystem.restoreEntry(result.logging_file_entry, function (entry) {
+                    if (chrome.runtime.lastError) {
+                        console.error(chrome.runtime.lastError.message);
```
Comment (mikeller) [inline src/js/tabs/logging.js:106]: What happens if you just do `console.error(chrome.runtime.lastError)`? NW.js should be smart enough to dump the error message and stack trace in this case.

Comment (haslinghuis) [reply src/js/tabs/logging.js:106]: This prints Object instead of the message property. Caller or Callee properties are not accessible in strict mode.
Was looking for a utility or common file to put this kind of stuff to de-deduplicate like in `serial.js` but then with an extra line: 
```
console.log((new Error).stack);
```

**Comment by haslinghuis** [comment]
This is the remaining list to change. Just wanted to see if Sonar is still confident with this.
```
src/js/tabs/firmware_flasher.js:873:                if (chrome.runtime.lastError) {
src/js/tabs/firmware_flasher.js:874:                    console.error(chrome.runtime.lastError.message);
src/js/tabs/firmware_flasher.js:1134:                if (chrome.runtime.lastError) {
src/js/tabs/firmware_flasher.js:1135:                    console.error(chrome.runtime.lastError.message);
src/js/tabs/vtx.js:583:            if (chrome.runtime.lastError) {
src/js/tabs/vtx.js:584:                console.error(chrome.runtime.lastError.message);
src/js/tabs/vtx.js:636:            if (chrome.runtime.lastError) {
src/js/tabs/vtx.js:637:                console.error(chrome.runtime.lastError.message);
src/js/tabs/vtx.js:689:            if (chrome.runtime.lastError) {
src/js/tabs/vtx.js:690:                console.error(chrome.runtime.lastError.message);
src/js/tabs/onboard_logging.js:613:                if (chrome.runtime.lastError.message !== "User cancelled") {
src/js/tabs/cli.js:151:                if (chrome.runtime.lastError) {
src/js/tabs/cli.js:152:                    console.error(chrome.runtime.lastError.message);
src/js/tabs/cli.js:207:                if (chrome.runtime.lastError) {
src/js/tabs/cli.js:208:                    console.error(chrome.runtime.lastError.message);
src/js/backup_restore.js:219:            if (chrome.runtime.lastError) {
src/js/backup_restore.js:220:                console.error(chrome.runtime.lastError.message);
src/js/backup_restore.js:291:        if (chrome.runtime.lastError) {
src/js/backup_restore.js:292:            console.error(chrome.runtime.lastError.message);
src/js/protocols/stm32usbdfu.js:106:    if (chrome.runtime.lastError) {
src/js/protocols/stm32usbdfu.js:107:        if(chrome.runtime.lastError.message)
src/js/protocols/stm32usbdfu.js:108:            console.log('reporting chrome error: ' + chrome.runtime.lastError.message);
src/js/protocols/stm32usbdfu.js:110:            console.log('reporting chrome error: ' + chrome.runtime.lastError);
src/js/cordova_chromeapi.js:16:            chrome.runtime.lastError = err;
src/js/cordova_chromeapi.js:23:            delete chrome.runtime.lastError;
```

**Comment by haslinghuis** [comment]
Instead of creating a common utility file I guess it was easier to use `main.js` as I found more common functions there.
Otherwise have to resort to imports on each file where it's used. Also found there was already such function in stm32usbdfu.js like I created in `serial.js`. Now all code uses the same `checkChromeRuntimeError()` function which should be called after each chrome API calls. The remaining code smells are going to be addressed in a follow up lexical scoping PR for protocol and firmware flashing code.

**Review by mikeller — APPROVED** [review]
