### PR TITLE
Fix gps_rescue_min_dth

### LINKED ISSUE #3546: UI range for `gps_rescue_descent_dist` is incorrect in `master`
### Describe the bug

please see closed PR https://github.com/betaflight/betaflight-configurator/pull/3542 .

Value range for `gps_rescue_descent_dist` is incorrect in Configurator UI. 

I will work on this single item... seems MSP version 1.45 is where `10` began to be used rather than `30`. (ref: https://github.com/betaflight/betaflight/pull/11579).

also found `5` was used for a stint: https://github.com/betaflight/betaflight/pull/11834 -- MSP was already version 1.45 here. i prefer not to add too much complexity and will not accommodate `5`.  firmware reverted to `10` in https://github.com/betaflight/betaflight/pull/12715 .

We may need to ask @ctzsnooze and @freasy for a complete list of needed UI ranges and what MSP they start.

### To Reproduce

n/a

### Expected behavior

n/a

### Configurator version

`master` 

### Flight controller configuration

_No response_

### Add any other context about the problem that you think might be relevant here

I suspect other ranges are out-of-sync as well.

### PR DESCRIPTION
**Pull request by haslinghuis**
Closes #3542
Closes #3546

### CODE REVIEW

**Comment by blckmn** [comment]
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

File: src/js/tabs/failsafe.js [hunk 1]
```diff
@@ -304,6 +304,10 @@ failsafe.initialize = function (callback) {
             $('input[name="gps_rescue_min_dth"]').attr("min", 20);
         }
 
+        if (semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_46)) {
+            $('input[name="gps_rescue_min_dth"]').attr("min", 10);
+        }
+
```
Comment (McGiverGim) [inline src/js/tabs/failsafe.js:310]: I think is cleaner to "join" in some way with the earlier if, because both affect the same paremeter. Maybe a simply `else` or a binary conditional operator or similar is enough.

**Review by McGiverGim — CHANGES_REQUESTED** [review]

File: src/js/tabs/failsafe.js (hunk 1 above)
Comment (haslinghuis) [reply src/js/tabs/failsafe.js:306]: Fixed :+1:

**Review by McGiverGim — COMMENTED** [review]
The code is far better but, we are sure about the values? Master seems 10, version 4.4 seems 20, version 4.3 seems 50. We support version 4.3? I suppose that yes. Then this binary must be only for version greater than 4.3, I suppose that 50 is the real value in the HTML code.

**Review by McGiverGim — APPROVED** [review]

**Review by nerdCopter — APPROVED** [review]
